const peliculas = 
[
    {nombre: "The Dark Knight", genero: "Acción", año: 2008},
    {nombre: "Inception", genero: "Ciencia ficción", año: 2010},
    {nombre: "Avatar", genero: "Ciencia ficción", año: 2009},
    {nombre: "The Avengers", genero: "Acción", año: 2012},
    {nombre: "The Social Network", genero: "Drama", año: 2010},
    {nombre: "Black Panther", genero: "Acción", año: 2018},
    {nombre: "The Revenant", genero: "Aventura", año: 2015},
    {nombre: "The Grand Budapest Hotel", genero: "Comedia", año: 2014},
    {nombre: "La La Land", genero: "Musical", año: 2016},
    {nombre: "Mad Max: Fury Road", genero: "Acción", año: 2015},
    {nombre: "The Shape of Water", genero: "Fantasía", año: 2017},
    {nombre: "Interstellar", genero: "Ciencia ficción", año: 2014 },
    { nombre: "Get Out", genero: "Terror", año: 2017 },
    { nombre: "Parasite", genero: "Drama", año: 2019 },
    { nombre: "Birdman", genero: "Drama", año: 2014 },
    { nombre: "The Martian", genero: "Ciencia ficción", año: 2015 },
    { nombre: "La La Land", genero: "Musical", año: 2016 },
    { nombre: "Moonlight", genero: "Drama", año: 2016 },
    { nombre: "The Shape of Water", genero: "Fantasía", año: 2017 },
    { nombre: "Inception", genero: "Ciencia ficción", año: 2010 },
]